apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
type: Opaque
data:
  # This is a placeholder - in real deployment, this would contain the actual tunnel token
  # The actual token would be base64 encoded and stored here
  # Example: cred.json: <base64-encoded-tunnel-token>
  cred.json: "eyJ0dW5uZWwiOiAiaW5rLWhvbWVsYWIiLCAiY3JlZGVudGlhbHMtZmlsZSI6ICIvZXRjL2NyZWQuanNvbiJ9Cg=="
